### PR TITLE
Fix volume slide

### PR DESCRIPTION
**Pull request by cheralathann**
Fixed

### CODE REVIEW

**Comment by dalemartyn** [comment]
Thanks! This is cool. I think the code could be cleaner if we wrote it `setIsMuted(e.detail.value === 0)`.

**Comment by cheralathann** [comment]
Great! That could be better and clean.

> Thanks! This is cool. I think the code could be cleaner if we wrote it `setIsMuted(e.detail.value === 0)`.

**Comment by dalemartyn** [comment]
Thanks!

**Comment by dalemartyn** [comment]
I actually found another bug with the volume slider... it wouldn't unmute if you dragged the slider after hitting the mute button, so I've updated the code a bit. 22f92c3

**Comment by cheralathann** [comment]
Good catch!! 👍 

> I actually found another bug with the volume slider... it wouldn't unmute if you dragged the slider after hitting the mute button, so I've updated the code a bit. [22f92c3](https://github.com/dalemartyn/podcast-player/commit/22f92c38cc72bbc4ee96b7766bb7faacb688e930)

**Pull request merged**
